package models;
// Generated 13-feb-2017 21:40:47 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Mesa generated by hbm2java
 */
public class Mesa implements java.io.Serializable {

	private Integer idMesa;
	private int capacidad;
	private boolean ocupada;
	private Set servicios = new HashSet(0);

	public Mesa() {
	}

	public Mesa(int capacidad, boolean ocupada) {
		this.capacidad = capacidad;
		this.ocupada = ocupada;
	}

	public Mesa(int capacidad, boolean ocupada, Set servicios) {
		this.capacidad = capacidad;
		this.ocupada = ocupada;
		this.servicios = servicios;
	}

	public Integer getIdMesa() {
		return this.idMesa;
	}

	public void setIdMesa(Integer idMesa) {
		this.idMesa = idMesa;
	}

	public int getCapacidad() {
		return this.capacidad;
	}

	public void setCapacidad(int capacidad) {
		this.capacidad = capacidad;
	}

	public boolean isOcupada() {
		return this.ocupada;
	}

	public void setOcupada(boolean ocupada) {
		this.ocupada = ocupada;
	}

	public Set getServicios() {
		return this.servicios;
	}

	public void setServicios(Set servicios) {
		this.servicios = servicios;
	}

}
