package models;
// Generated 15-feb-2017 4:57:18 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto implements java.io.Serializable {

	private Integer idProducto;
	private String denominacion;
	private String tipoProducto;
	private BigDecimal precio;
	private String descripcion;
	private Set comandas = new HashSet(0);

	public Producto() {
	}

	public Producto(String denominacion, String tipoProducto, BigDecimal precio) {
		this.denominacion = denominacion;
		this.tipoProducto = tipoProducto;
		this.precio = precio;
	}

	public Producto(String denominacion, String tipoProducto, BigDecimal precio, String descripcion, Set comandas) {
		this.denominacion = denominacion;
		this.tipoProducto = tipoProducto;
		this.precio = precio;
		this.descripcion = descripcion;
		this.comandas = comandas;
	}

	public Integer getIdProducto() {
		return this.idProducto;
	}

	public void setIdProducto(Integer idProducto) {
		this.idProducto = idProducto;
	}

	public String getDenominacion() {
		return this.denominacion;
	}

	public void setDenominacion(String denominacion) {
		this.denominacion = denominacion;
	}

	public String getTipoProducto() {
		return this.tipoProducto;
	}

	public void setTipoProducto(String tipoProducto) {
		this.tipoProducto = tipoProducto;
	}

	public BigDecimal getPrecio() {
		return this.precio;
	}

	public void setPrecio(BigDecimal precio) {
		this.precio = precio;
	}

	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	public Set getComandas() {
		return this.comandas;
	}

	public void setComandas(Set comandas) {
		this.comandas = comandas;
	}

}
